name: Test
on:
  push:
  pull_request:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:

permissions: {}
jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@bd27009d5f178c0a88d42f7b07e6a3c7623ed768 # v7.0.8
    with: { npm: false, superlinter: false }
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write
